DELETE FROM BATCH_STEP_EXECUTION_CONTEXT;
DELETE FROM BATCH_STEP_EXECUTION;
DELETE FROM BATCH_JOB_EXECUTION_CONTEXT;
DELETE FROM BATCH_JOB_EXECUTION_PARAMS;
DELETE FROM BATCH_JOB_EXECUTION;
DELETE FROM BATCH_JOB_INSTANCE;

DROP TABLE IF EXISTS daily_stock_summary;
DROP TABLE IF EXISTS stock_history;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS warehouse;
DROP TABLE IF EXISTS item_master;

CREATE TABLE item_master (
    item_code VARCHAR(30) PRIMARY KEY,
    item_name VARCHAR(100) NOT NULL
);

CREATE TABLE warehouse (
    warehouse_id BIGINT PRIMARY KEY,
    warehouse_name VARCHAR(100) NOT NULL
);

CREATE TABLE inventory (
    inventory_id BIGINT PRIMARY KEY,
    item_code VARCHAR(30) NOT NULL REFERENCES item_master(item_code),
    warehouse_id BIGINT NOT NULL REFERENCES warehouse(warehouse_id),
    quantity INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE stock_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT NOT NULL REFERENCES inventory(inventory_id),
    movement_type VARCHAR(3) NOT NULL,
    quantity INTEGER NOT NULL,
    before_quantity INTEGER NOT NULL,
    after_quantity INTEGER NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE daily_stock_summary (
    business_date DATE NOT NULL,
    item_code VARCHAR(30) NOT NULL,
    warehouse_id BIGINT NOT NULL,
    total_in_quantity INTEGER NOT NULL,
    total_out_quantity INTEGER NOT NULL,
    movement_count INTEGER NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (business_date, item_code, warehouse_id)
);

INSERT INTO item_master (item_code, item_name) VALUES
    ('ITEM001', '六角ボルト'),
    ('ITEM002', '六角ナット');

INSERT INTO warehouse (warehouse_id, warehouse_name) VALUES
    (1, '東京倉庫'),
    (2, '大阪倉庫');

INSERT INTO inventory (
    inventory_id, item_code, warehouse_id, quantity, status, updated_at
) VALUES
    (1001, 'ITEM001', 1, 120, 'AVAILABLE', '2026-09-18 00:00:00+00:00'),
    (1002, 'ITEM001', 2, 40, 'AVAILABLE', '2026-09-18 00:00:00+00:00'),
    (1003, 'ITEM002', 1, 75, 'AVAILABLE', '2026-09-18 00:00:00+00:00');

INSERT INTO stock_history (
    inventory_id, movement_type, quantity,
    before_quantity, after_quantity, processed_at
) VALUES
    (1001, 'IN',   5, 117, 122, '2026-09-18 01:00:00+00:00'),
    (1001, 'OUT',  2, 122, 120, '2026-09-18 02:00:00+00:00'),
    (1002, 'IN',   7,  40,  47, '2026-09-18 03:00:00+00:00'),
    (1003, 'IN',  10,  75,  85, '2026-09-18 04:00:00+00:00'),
    (1003, 'OUT',  4,  85,  81, '2026-09-18 05:00:00+00:00'),
    (1001, 'IN',  99, 120, 219, '2026-09-17 01:00:00+00:00');
