DROP TABLE IF EXISTS stock_history;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS warehouse;
DROP TABLE IF EXISTS item_master;

CREATE TABLE item_master (
    item_code VARCHAR(30) PRIMARY KEY,
    item_name VARCHAR(100) NOT NULL
);

CREATE TABLE warehouse (
    warehouse_id BIGINT PRIMARY KEY,
    warehouse_name VARCHAR(100) NOT NULL
);

CREATE TABLE inventory (
    inventory_id BIGINT PRIMARY KEY,
    item_code VARCHAR(30) NOT NULL,
    warehouse_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_inventory_item FOREIGN KEY (item_code) REFERENCES item_master(item_code),
    CONSTRAINT fk_test_inventory_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouse(warehouse_id)
);

CREATE TABLE stock_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id BIGINT NOT NULL,
    movement_type VARCHAR(3) NOT NULL,
    quantity INTEGER NOT NULL,
    before_quantity INTEGER NOT NULL,
    after_quantity INTEGER NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_history_inventory FOREIGN KEY (inventory_id) REFERENCES inventory(inventory_id)
);
